name: Docker Image Build and Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: uburuntu/kaldi-vosk-server
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Docker Login
        run: |
          echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin

      - name: Docker Configuration
        run: |
          echo "{" > /etc/docker/daemon.json
          echo "    \"MTU\":1300" > /etc/docker/daemon.json
          echo "}" > /etc/docker/daemon.json

      - name: Run Buildx (push image)
        run: |
          docker buildx build \
          --platform ${DOCKER_TARGET_PLATFORM} \
          --tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:arm64 \
          --file ./docker/Dockerfile \
          --output type=image,push=true .
