name: Docker Image Build and Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image for ARMv7
      uses: docker/build-push-action@v1
      with:
        path: docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: uburuntu/kaldi-vosk-server
        tags: armv7
        build_args: ARCH=ARMV7

    - name: Build and push Docker image for ARMv8
      uses: docker/build-push-action@v1
      with:
        path: docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: uburuntu/kaldi-vosk-server
        tags: armv8
        build_args: ARCH=ARMV8
